##Intro

In [1]:
import tensorflow as tf

In [2]:
x = tf.range(10)
print(tf.size(x))
print(x)
x = tf.reshape(x, (2,5))
x

tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int32)>

In [3]:
print(tf.zeros((2,3,4)))
print(tf.ones((1,2,4)))

tf.Tensor(
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 2, 4), dtype=float32)


In [4]:
#for randomly sampling values from some random distribution
tf.random.normal(shape=[2,3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7850897 , -0.9538179 ,  0.2451088 ],
       [-0.955983  , -0.3464054 ,  0.60390747]], dtype=float32)>

In [5]:
#creating tensor from python lists
tf.constant([[1,3,4],[1,4,2],[5,7,6]])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 3, 4],
       [1, 4, 2],
       [5, 7, 6]], dtype=int32)>

##Operations

In [6]:
#common standard operations can be done element wise in same shape array
x = tf.constant([1.0, 2, 4, 8])
y = tf.constant([2.0, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # The ** operator is exponentiation

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 3.,  4.,  6., 10.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-1.,  0.,  2.,  6.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 2.,  4.,  8., 16.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5, 1. , 2. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4., 16., 64.], dtype=float32)>)

In [7]:
#exponentiation operations can also be done
tf.exp(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=
array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03],
      dtype=float32)>

In [8]:
#linear algebra operations(dot product, matmul) can also be carried out
#concatting two tensors only when tensors are rectangular
a = tf.reshape(tf.range(12), shape=[3,4])
b = tf.constant([[1,2,34,5],[5,6,7,8],[2,4,6,8]])
tf.concat([a,b], axis=1),tf.concat([a,b], axis=0)

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 0,  1,  2,  3,  1,  2, 34,  5],
        [ 4,  5,  6,  7,  5,  6,  7,  8],
        [ 8,  9, 10, 11,  2,  4,  6,  8]], dtype=int32)>,
 <tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 1,  2, 34,  5],
        [ 5,  6,  7,  8],
        [ 2,  4,  6,  8]], dtype=int32)>)

In [9]:
#can create a boolean tensor
a==b

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])>

In [10]:
#summing all elements in tensor
tf.reduce_sum(b)

<tf.Tensor: shape=(), dtype=int32, numpy=88>

##Broadcasting

In [11]:
#used when the shapes are not same (expand one/both tensors to equal shape and then operation)
a = tf.reshape(tf.range(3), (3,1))
b = tf.reshape(tf.range(2), (1,2))
a, b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]], dtype=int32)>)

In [12]:
a + b, a * b, (a+b).shape

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 1],
        [1, 2],
        [2, 3]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[0, 0],
        [0, 1],
        [0, 2]], dtype=int32)>, TensorShape([3, 2]))

##Indexing and Slicing

In [13]:
#similar to python
tmp = a + b
print(tmp[-1]) #last row of multid tensor
print(tmp[0:2]) #slicing

tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int32)


In [14]:
#tensors are immutable
tmp = a+b
#tmp[1,1] = 9 #will throw error
x_var = tf.Variable(tmp)
x_var[1,1].assign(6)
x_var

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[0, 1],
       [1, 6],
       [2, 3]], dtype=int32)>

In [18]:
a = tf.reshape(tf.range(12, dtype=tf.float32),(3,4))
X_var = tf.Variable(a)
X_var[0:2, :].assign(tf.ones(X_var[0:2,:].shape, dtype = tf.float32) * 12)
X_var

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

##Saving Memory

In [30]:
#python derefences pointer to object when it is reassigned,
# This might be undesirable for two reasons. 
# First, we do not want to run around allocating memory unnecessarily all the time. 
# In machine learning, we might have hundreds of megabytes of parameters and update all of them multiple times per second. 
# Typically, we will want to perform these updates in place. Second, we might point at the same parameters from multiple variables. 
# If we do not update in place, other references will still point to the old memory location,
#  making it possible for parts of our code to inadvertently reference stale parameters.

X = tf.reshape(tf.range(12, dtype=tf.float32), (3, 4))
Y = tf.constant([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
z = tf.Variable(tf.zeros_like(Y))
print(f"id(z):{id(z)}")
z.assign(X+Y)
print(f"id(z):{id(z)}")

id(z):140001483122192
id(z):140001483122192


In [31]:
# TensorFlow provides the tf.function decorator to wrap computation inside of a TensorFlow graph that gets compiled and optimized before running. 
# This allows TensorFlow to prune unused values, and to re-use prior allocations that are no longer needed. This minimizes the memory overhead of TensorFlow computations.

@tf.function
def computation(X, Y):
    Z = tf.zeros_like(Y)  # This unused value will be pruned out
    A = X + Y  # Allocations will be re-used when no longer needed
    B = A + Y
    C = B + Y
    return C + Y

computation(X, Y)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 8.,  5., 18., 15.],
       [ 8., 13., 18., 23.],
       [24., 21., 18., 15.]], dtype=float32)>

##Converting to Python objects


In [35]:
import numpy
a = tf.constant([3,5]).numpy()
a

array([3, 5], dtype=int32)