##Scalars

In [1]:
import tensorflow as tf

x = tf.constant([3.0])
y = tf.constant([2.0])

x+y, x*y, x/y, x**y

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([5.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([6.], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.5], dtype=float32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([9.], dtype=float32)>)

##Vectors

In [2]:
x = tf.range(4)
x, x[3]

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [3]:
len(x), x.shape #shape returns number of elements in a single axis

(4, TensorShape([4]))

##Matrices

In [4]:
A = tf.reshape(tf.range(20), (5,4))
A, A.shape

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=int32)>, TensorShape([5, 4]))

In [5]:
tf.transpose(A)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]], dtype=int32)>

In [6]:
B = tf.constant([[1, 2, 3], [2, 0, 4], [3, 4, 5]]) #symmetric matrix
B

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]], dtype=int32)>

In [7]:
B == tf.transpose(B)

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

##Tensors

In [8]:
#n dimensional arrays with arbitrary number of axes
X = tf.reshape(tf.range(24), (2,3,4))
X

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [31]:
#tensor arithmetic
A = tf.reshape(tf.range(20), (5,4))
B = A 
A, A+B #same shape performs elementwise addition

(<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]], dtype=int32)>,
 <tf.Tensor: shape=(5, 4), dtype=int32, numpy=
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]], dtype=int32)>)

In [11]:
A*B

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)>

In [12]:
a = 2
X = tf.reshape(tf.range(24), (2,3,4))
a+X, X**a #doesnt change shape of tensor

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[  0,   1,   4,   9],
         [ 16,  25,  36,  49],
         [ 64,  81, 100, 121]],
 
        [[144, 169, 196, 225],
         [256, 289, 324, 361],
         [400, 441, 484, 529]]], dtype=int32)>)

##Reduction/ NonReduction

```
# This is formatted as code
```



In [25]:
x = tf.range(4, dtype=tf.float32)
x, tf.reduce_sum(x) #sum of all elements in tensor

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [14]:
A_sum_axis0 = tf.reduce_sum(A, axis=0)
A_sum_axis0, A_sum_axis0.shape

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([40, 45, 50, 55], dtype=int32)>,
 TensorShape([4]))

In [15]:
A_sum_axis1 = tf.reduce_sum(A, axis=1)
A_sum_axis1

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 22, 38, 54, 70], dtype=int32)>

In [16]:
tf.reduce_sum(A, axis = [0,1])#sums all elements

<tf.Tensor: shape=(), dtype=int32, numpy=190>

In [17]:
tf.reduce_mean(A), tf.reduce_sum(A) / tf.size(A).numpy()

(<tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=float64, numpy=9.5>)

In [18]:
tf.reduce_mean(A, axis=0), tf.reduce_sum(A, axis=0) / A.shape[0] #calculate mean across specific dimension

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 8,  9, 10, 11], dtype=int32)>,
 <tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 8.,  9., 10., 11.])>)

In [19]:
#sometimes helpful to keep number of axes unchanged
sum_A = tf.reduce_sum(A, axis=1, keepdims=True)
sum_A

<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[ 6],
       [22],
       [38],
       [54],
       [70]], dtype=int32)>

In [20]:
A/sum_A #using broadcasting

<tf.Tensor: shape=(5, 4), dtype=float64, numpy=
array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])>

In [21]:
#cumulative sum across axis
tf.cumsum(A, axis=0)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]], dtype=int32)>

##Dot Products

In [26]:
y = tf.ones(4, dtype=tf.float32)
x,y, tf.tensordot(x,y,axes=1)

(<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=6.0>)

In [27]:
# same as elementwise mul and then reducesum
tf.reduce_sum(x*y)
# weighted sum of the values in  x  according to the weights  w  could be expressed as the dot product  x⊤w . When the weights are non-negative and sum to one 
#(i.e.,  (∑di=1wi=1) ), the dot product expresses a weighted average. 

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

##Matrix Vector Products

In [35]:
import numpy as np

A.shape, x.shape, np.dot(A,x)

(TensorShape([5, 4]), TensorShape([4]), array([ 14.,  38.,  62.,  86., 110.]))

In [38]:
B = tf.ones((4,3), tf.float32)
np.dot(A,B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

##Norms

In [39]:
#norms tell us how big a vector is
u = tf.constant([3.0, -4.0])
np.linalg.norm(u) #l2 norm

5.0

In [40]:
#l1 norm (less influenced to outliers)
np.abs(u).sum()

7.0

In [42]:
#frobenius norm
np.linalg.norm(np.ones((4,9)))

6.0

##Exercises

In [43]:
A == tf.transpose(tf.transpose(A))

<tf.Tensor: shape=(5, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

In [52]:
A = tf.reshape(range(20), (4,5))
B = tf.reshape(range(1, 21), (4,5))
tf.transpose(A) + tf.transpose(B) == tf.transpose(A+B)

<tf.Tensor: shape=(5, 4), dtype=bool, numpy=
array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])>

In [55]:
np.array(A).sum(axis=1), np.array(A)
# np.array(A) / np.array(A).sum(axis=1) #cannot broadcast as dims dont match

(array([10, 35, 60, 85]), array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]], dtype=int32))